service: react-word-counter-frontend

provider:
  name: aws
  stage: dev
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: word-counter-bucket
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html